### ISSUE TITLE
iOS 18 as min deployment target is not compatible with current Xcode 15.x LTS releases

### ISSUE THREAD

**Issue by wilbarrios** [ahrchen/iOSUnit1DemoPHPicker#1]
## Problem

Professors are not able to see available targets when using Xcode official releases, this is because the min iOS required is 18

## Solution

Set a lower version i.e. `17.0` as min iOS will support the majority of Xcode 15.x.

![image](https://github.com/user-attachments/assets/5bc2e73c-e213-43cc-8b4c-57d10b51d3e8)

**Comment by ahrchen** [comment]
Thanks, it has been set to iOS 17.0. I will look through the other projects and set the minimum deployment to 17.0 as well.
